In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
df = pd.read_csv('C:/Users/Ron/Documents/core_dataset.csv')

In [4]:
df=df.iloc[0:301]

In [5]:
df.dtypes

Employee Name           object
Employee Number        float64
State                   object
Zip                    float64
DOB                     object
Age                    float64
Sex                     object
MaritalDesc             object
CitizenDesc             object
Hispanic/Latino         object
RaceDesc                object
Date of Hire            object
Date of Termination     object
Reason For Term         object
Employment Status       object
Department              object
Position                object
Pay Rate               float64
Manager Name            object
Employee Source         object
Performance Score       object
dtype: object

In [6]:
df = df.rename(columns={'Date of Hire': 'DateofHire', 'Date of Termination':'DateofTermination', 'Pay Rate': 'PayRate', 'Employee Name': 'EmployeeName',
                          'Employee Number': 'EmployeeID', 'Reason For Term': 'ReasonForTerm', 'Manager Name':'ManagerName', 'Employee Source': 'EmployeeSource',
                            'Performance Score': 'PerformanceScore', 'Zip': 'ZipCode', 'Employment Status': 'EmploymentStatus',
                       'Hispanic/Latino': 'HispanicLatino'})

In [7]:
df

,EmployeeName,EmployeeID,State,ZipCode,DOB,Age,Sex,MaritalDesc,CitizenDesc,HispanicLatino,...,DateofHire,DateofTermination,ReasonForTerm,EmploymentStatus,Department,Position,PayRate,ManagerName,EmployeeSource,PerformanceScore
0,"Brown, Mia",1.103024e+09,MA,1450.0,11/24/1985,32.0,Female,Married,US Citizen,No,...,10/27/2008,NaN,N/A - still employed,Active,Admin Offices,Accountant I,28.50,Brandon R. LeBlanc,Diversity Job Fair,Fully Meets
1,"LaRotonda, William",1.106027e+09,MA,1460.0,4/26/1984,33.0,Male,Divorced,US Citizen,No,...,1/6/2014,NaN,N/A - still employed,Active,Admin Offices,Accountant I,23.00,Brandon R. LeBlanc,Website Banner Ads,Fully Meets
2,"Steans, Tyrone",1.302053e+09,MA,2703.0,9/1/1986,31.0,Male,Single,US Citizen,No,...,9/29/2014,NaN,N/A - still employed,Active,Admin Offices,Accountant I,29.00,Brandon R. LeBlanc,Internet Search,Fully Meets
3,"Howard, Estelle",1.211051e+09,MA,2170.0,9/16/1985,32.0,Female,Married,US Citizen,No,...,2/16/2015,4/15/2015,N/A - still employed,Active,Admin Offices,Administrative Assistant,21.50,Brandon R. LeBlanc,Pay Per Click - Google,N/A- too early to review
4,"Singh, Nan",1.307060e+09,MA,2330.0,5/19/1988,29.0,Female,Single,US Citizen,No,...,5/1/2015,NaN,N/A - still employed,Active,Admin Offices,Administrative Assistant,16.56,Brandon R. LeBlanc,Website Banner Ads,N/A- too early to review
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
296,"Patronick, Luke",1.112031e+09,MA,1844.0,2/20/1979,38.0,Male,Single,US Citizen,No,...,11/7/2011,9/7/2015,Another position,Voluntarily Terminated,Software Engineering,Software Engineer,52.25,Alex Sweetwater,Diversity Job Fair,Exceeds
297,"Saada, Adell",1.012023e+09,MA,2132.0,7/24/1986,31.0,Female,Married,US Citizen,No,...,11/5/2012,NaN,N/A - still employed,Active,Software Engineering,Software Engineer,49.25,Alex Sweetwater,Pay Per Click - Google,Fully Meets
298,"Szabo, Andrew",1.201031e+09,MA,2140.0,5/6/1983,34.0,Male,Single,US Citizen,No,...,7/7/2014,NaN,N/A - still employed,Active,Software Engineering,Software Engineer,48.00,Alex Sweetwater,MBTA ads,Exceptional
299,"True, Edward",1.102024e+09,MA,2451.0,6/14/1983,34.0,Male,Single,Non-Citizen,No,...,2/18/2013,4/15/2014,medical issues,Voluntarily Terminated,Software Engineering,Software Engineer,45.42,Alex Sweetwater,Diversity Job Fair,Fully Meets
300,"Sweetwater, Alex",1.001645e+09,MA,2184.0,11/22/1966,51.0,Male,Single,US Citizen,No,...,8/15/2011,NaN,N/A - still employed,Active,Software Engineering,Software Engineering Manager,27.00,Jennifer Zamora,Search Engine - Google Bing Yahoo,Fully Meets

In [8]:
df['DOB']=pd.to_datetime(df['DOB'])

In [9]:
df['DateofHire'] = pd.to_datetime(df['DateofHire'])

In [10]:
df['DateofTermination'] = pd.to_datetime(df['DateofTermination'])

In [11]:
df.dtypes

EmployeeName                 object
EmployeeID                  float64
State                        object
ZipCode                     float64
DOB                  datetime64[ns]
Age                         float64
Sex                          object
MaritalDesc                  object
CitizenDesc                  object
HispanicLatino               object
RaceDesc                     object
DateofHire           datetime64[ns]
DateofTermination    datetime64[ns]
ReasonForTerm                object
EmploymentStatus             object
Department                   object
Position                     object
PayRate                     float64
ManagerName                  object
EmployeeSource               object
PerformanceScore             object
dtype: object

In [12]:
df['Salary'] = df.PayRate*40*52

In [13]:
df

,EmployeeName,EmployeeID,State,ZipCode,DOB,Age,Sex,MaritalDesc,CitizenDesc,HispanicLatino,...,DateofTermination,ReasonForTerm,EmploymentStatus,Department,Position,PayRate,ManagerName,EmployeeSource,PerformanceScore,Salary
0,"Brown, Mia",1.103024e+09,MA,1450.0,1985-11-24,32.0,Female,Married,US Citizen,No,...,NaT,N/A - still employed,Active,Admin Offices,Accountant I,28.50,Brandon R. LeBlanc,Diversity Job Fair,Fully Meets,59280.0
1,"LaRotonda, William",1.106027e+09,MA,1460.0,1984-04-26,33.0,Male,Divorced,US Citizen,No,...,NaT,N/A - still employed,Active,Admin Offices,Accountant I,23.00,Brandon R. LeBlanc,Website Banner Ads,Fully Meets,47840.0
2,"Steans, Tyrone",1.302053e+09,MA,2703.0,1986-09-01,31.0,Male,Single,US Citizen,No,...,NaT,N/A - still employed,Active,Admin Offices,Accountant I,29.00,Brandon R. LeBlanc,Internet Search,Fully Meets,60320.0
3,"Howard, Estelle",1.211051e+09,MA,2170.0,1985-09-16,32.0,Female,Married,US Citizen,No,...,2015-04-15,N/A - still employed,Active,Admin Offices,Administrative Assistant,21.50,Brandon R. LeBlanc,Pay Per Click - Google,N/A- too early to review,44720.0
4,"Singh, Nan",1.307060e+09,MA,2330.0,1988-05-19,29.0,Female,Single,US Citizen,No,...,NaT,N/A - still employed,Active,Admin Offices,Administrative Assistant,16.56,Brandon R. LeBlanc,Website Banner Ads,N/A- too early to review,34444.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
296,"Patronick, Luke",1.112031e+09,MA,1844.0,1979-02-20,38.0,Male,Single,US Citizen,No,...,2015-09-07,Another position,Voluntarily Terminated,Software Engineering,Software Engineer,52.25,Alex Sweetwater,Diversity Job Fair,Exceeds,108680.0
297,"Saada, Adell",1.012023e+09,MA,2132.0,1986-07-24,31.0,Female,Married,US Citizen,No,...,NaT,N/A - still employed,Active,Software Engineering,Software Engineer,49.25,Alex Sweetwater,Pay Per Click - Google,Fully Meets,102440.0
298,"Szabo, Andrew",1.201031e+09,MA,2140.0,1983-05-06,34.0,Male,Single,US Citizen,No,...,NaT,N/A - still employed,Active,Software Engineering,Software Engineer,48.00,Alex Sweetwater,MBTA ads,Exceptional,99840.0
299,"True, Edward",1.102024e+09,MA,2451.0,1983-06-14,34.0,Male,Single,Non-Citizen,No,...,2014-04-15,medical issues,Voluntarily Terminated,Software Engineering,Software Engineer,45.42,Alex Sweetwater,Diversity Job Fair,Fully Meets,94473.6
300,"Sweetwater, Alex",1.001645e+09,MA,2184.0,1966-11-22,51.0,Male,Single,US Citizen,No,...,NaT,N/A - still employed,Active,Software Engineering,Software Engineering Manager,27.00,Jennifer Zamora,Search Engine - Google Bing Yahoo,Fully Meets,56160.0

In [14]:
df['MaritalDesc']=df['MaritalDesc'].str.capitalize()

In [15]:
df.head(53)

,EmployeeName,EmployeeID,State,ZipCode,DOB,Age,Sex,MaritalDesc,CitizenDesc,HispanicLatino,...,DateofTermination,ReasonForTerm,EmploymentStatus,Department,Position,PayRate,ManagerName,EmployeeSource,PerformanceScore,Salary
0,"Brown, Mia",1.103024e+09,MA,1450.0,1985-11-24,32.0,Female,Married,US Citizen,No,...,NaT,N/A - still employed,Active,Admin Offices,Accountant I,28.50,Brandon R. LeBlanc,Diversity Job Fair,Fully Meets,59280.0
1,"LaRotonda, William",1.106027e+09,MA,1460.0,1984-04-26,33.0,Male,Divorced,US Citizen,No,...,NaT,N/A - still employed,Active,Admin Offices,Accountant I,23.00,Brandon R. LeBlanc,Website Banner Ads,Fully Meets,47840.0
2,"Steans, Tyrone",1.302053e+09,MA,2703.0,1986-09-01,31.0,Male,Single,US Citizen,No,...,NaT,N/A - still employed,Active,Admin Offices,Accountant I,29.00,Brandon R. LeBlanc,Internet Search,Fully Meets,60320.0
3,"Howard, Estelle",1.211051e+09,MA,2170.0,1985-09-16,32.0,Female,Married,US Citizen,No,...,2015-04-15,N/A - still employed,Active,Admin Offices,Administrative Assistant,21.50,Brandon R. LeBlanc,Pay Per Click - Google,N/A- too early to review,44720.0
4,"Singh, Nan",1.307060e+09,MA,2330.0,1988-05-19,29.0,Female,Single,US Citizen,No,...,NaT,N/A - still employed,Active,Admin Offices,Administrative Assistant,16.56,Brandon R. LeBlanc,Website Banner Ads,N/A- too early to review,34444.8
5,"Smith, Leigh Ann",7.110077e+08,MA,1844.0,1987-06-14,30.0,Female,Married,US Citizen,No,...,2013-09-25,career change,Voluntarily Terminated,Admin Offices,Administrative Assistant,20.50,Brandon R. LeBlanc,Diversity Job Fair,Fully Meets,42640.0
6,"LeBlanc, Brandon R",1.102024e+09,MA,1460.0,1984-06-10,33.0,Male,Married,US Citizen,No,...,NaT,N/A - still employed,Active,Admin Offices,Shared Services Manager,55.00,Janet King,Monster.com,Fully Meets,114400.0
7,"Quinn, Sean",1.206043e+09,MA,2045.0,1984-11-06,33.0,Male,Married,Eligible NonCitizen,No,...,2015-08-15,career change,Voluntarily Terminated,Admin Offices,Shared Services Manager,55.00,Janet King,Diversity Job Fair,Fully Meets,114400.0
8,"Boutwell, Bonalyn",1.307060e+09,MA,2468.0,1987-04-04,30.0,Female,Married,US Citizen,No,...,NaT,N/A - still employed,Active,Admin Offices,Sr. Accountant,34.95,Brandon R. LeBlanc,Diversity Job Fair,90-day meets,72696.0
9,"Foster-Baker, Amy",1.201031e+09,MA,2050.0,1979-04-16,38.0,Female,Married,US Citizen,no,...,NaT,N/A - still employed,Active,Admin Offices,Sr. Accountant,34.95,Board of Directors,Other,Fully Meets,72696.0
10,"King, Janet",1.001495e+09,MA,1902.0,1954-09-21,63.0,Female,Married,US Citizen,Yes,...,NaT,N/A - still employed,Active,Executive Office,President & CEO,80.00,Board of Directors,Pay Per Click - Google,Fully Meets,166400.0
11,"Zamora, Jennifer",1.112031e+09,MA,2067.0,1979-08-30,38.0,Female,Single,US Citizen,No,...,NaT,N/A - still employed,Active,IT/IS,CIO,65.00,Janet King,Employee Referral,Exceptional,135200.0
12,"Becker, Renee",1.102024e+09,MA,2026.0,1986-04-04,31.0,Female,Single,US Citizen,Yes,...,2015-09-12,performance,Terminated for Cause,IT/IS,Database Administrator,43.00,Simon Roup,Search Engine - Google Bing Yahoo,Fully Meets,89440.0
13,"Goble, Taisha",9.050137e+08,MA,2127.0,1971-10-23,46.0,Female,Single,US Citizen,No,...,2015-03-15,"no-call, no-show",Terminated for Cause,IT/IS,Database Administrator,48.50,Simon Roup,Glassdoor,Fully Meets,100880.0
14,"Hernandez, Daniff",1.410071e+09,MA,1960.0,1986-08-07,31.0,Male,Married,US Citizen,No,...,2015-02-22,"no-call, no-show",Terminated for Cause,IT/IS,Database Administrator,40.10,Simon Roup,Employee Referral,N/A- too early to review,83408.0
15,"Horton, Jayne",1.105026e+09,MA,2493.0,1984-02-21,33.0,Female,Single,US Citizen,No,...,NaT,N/A - still employed,Active,IT/IS,Database Administrator,34.00,Simon Roup,Glassdoor,N/A- too early to review,70720.0
16,"Johnson, Noelle",1.003018e+09,MA,2301.0,1986-11-07,31.0,Female,Married,US Citizen,No,...,NaT,N/A - still employed,Leave of Absence,IT/IS,Database Administrator,40.00,Simon Roup,Glassdoor,90-day meets,83200.0
17,"Murray, Thomas",1.406068e+09,TX,78230.0,1988-07-04,29.0,Male,Divorced,US Citizen,No,...,NaT,N/A - still employed,Active,IT/IS,Database Administrator,35.50,Simon Roup,Diversity Job Fair,Exceptional,73840.0
18,"Pearson, Randall",1.102024e+09,MA,2747.0,1984-09-05,33.0,Male,Married,US Citizen,No,...,2016-05-01,performance,Voluntarily Terminated,IT/IS,Database Administrator,41.00,Simon Roup,Employee Referral,Fully Meets,85280.0
19,"Petrowsky, Thelma",1.108028e+09,MA,1886.0,1984-09-16,33.0,Female,Married,US Citizen,No,...,NaT,N/A - still employed,Active,IT/IS,Database Administrator,42.75,Simon Roup,Employee Referral,Exceptional,88920.0
20,"Roby, Lori",1.407069e+09,MA,1886.0,1981-10-11,36.0,Female,Married,US Citizen,No,...,NaT,N/A - still employed,Active,IT/IS,Database Administrator,39.55,Simon Roup,Employee Referral,Fully Meets,82264.0
21,"Rogers, Ivan",1.203032e+09,MA,1810.0,1986-08-26,31.0,Male,Married,US Citizen,No,...,NaT,N/A - still employed,Active,IT/IS,Database Administrator,42.20,Simon Roup,Pay Per Click - Google,N/A- too early to review,87776.0
22,"Salter, Jason",1.111030e+09,MA,2452.0,1987-12-17,30.0,Male,Divorced,US Citizen,No,...,2015-10-31,hours,Voluntarily Terminated,IT/IS,Database Administrator,45.00,Simon Roup,Vendor Referral,90-day meets,93600.0
23,"Simard, Kramer",8.080103e+08,MA,2110.0,1970-02-08,47.0,Male,Married,US Citizen,Yes,...,NaT,N/A - still employed,Active,IT/IS,Database Administrator,30.20,Simon Roup,Employee Referral,90-day meets,62816.0
24,"Zhou, Julia",1.110030e+09,MA,2148.0,1979-02-24,38.0,Female,Single,US Citizen,No,...,NaT,N/A - still employed,Active,IT/IS,Database Administrator,31.40,Simon Roup,Employee Referral,90-day meets,65312.0
25,"Foss, Jason",1.192991e+09,MA,1460.0,1980-07-05,37.0,Male,Single,US Citizen,No,...,NaT,N/A - still employed,Active,IT/IS,IT Director,65.00,Jennifer Zamora,Professional Society,Exceptional,135200.0
26,"Roup,Simon",1.106027e+09,MA,2481.0,1973-04-05,44.0,Male,Single,US Citizen,No,...,NaT,N/A - still employed,Active,IT/IS,IT Manager - DB,62.00,Jennifer Zamora,Professional Society,Fully Meets,128960.0
27,"Ruiz, Ricardo",1.001175e+09,MA,1915.0,1964-01-04,54.0,Male,Divorced,US Citizen,No,...,2015-11-04,hours,Voluntarily Terminated,IT/IS,IT Manager - DB,21.00,Jennifer Zamora,Diversity Job Fair,Fully Meets,43680.0
28,"Monroe, Peter",1.011023e+09,MA,2134.0,1986-10-05,31.0,Male,Married,Eligible NonCitizen,Yes,...,NaT,N/A - still employed,Active,IT/IS,IT Manager - Infra,63.00,Jennifer Zamora,Diversity Job Fair,Needs Improvement,131040.0
29,"Dougall, Eric",1.101024e+09,MA,1886.0,1970-07-09,47.0,Male,Single,US Citizen,No,...,NaT,N/A - still employed,Active,IT/IS,IT Manager - Support,64.00,Jennifer Zamora,Professional Society,Exceeds,133120.0
30,"Clayton, Rick",1.301053e+09,MA,2170.0,1985-09-05,32.0,Male,Single,US Citizen,No,...,NaT,N/A - still employed,Active,IT/IS,IT Support,28.99,Eric Dougall,Glassdoor,Fully Meets,60299.2
31,"Galia, Lisa",1.501072e+09,CT,6040.0,1968-07-06,49.0,Female,Single,US Citizen,No,...,NaT,N/A - still employed,Active,IT/IS,IT Support,31.40,Eric Dougall,Vendor Referral,Fully Meets,65312.0
32,"Lindsay, Leonara",6.020003e+08,CT,6070.0,1988-10-05,29.0,Female,Single,US Citizen,Yes,...,NaT,N/A - still employed,Active,IT/IS,IT Support,26.00,Eric Dougall,Diversity Job Fair,Exceeds,54080.0
33,"Soto, Julia",1.203032e+09,MA,2360.0,1973-03-12,44.0,Female,Married,US Citizen,No,...,NaT,N/A - still employed,Active,IT/IS,IT Support,27.49,Eric Dougall,Information Session,Fully Meets,57179.2
34,"Bacong, Alejandro",1.212052e+09,MA,1886.0,1988-01-07,30.0,Male,Divorced,US Citizen,No,...,NaT,N/A - still employed,Active,IT/IS,Network Engineer,45.00,Peter Monroe,Glassdoor,90-day meets,93600.0
35,"Cisco, Anthony",1.102024e+09,MA,2135.0,1989-11-24,28.0,Male,Married,US Citizen,Yes,...,NaT,N/A - still employed,Active,IT/IS,Network Engineer,42.00,Peter Monroe,Information Session,N/A- too early to review,87360.0
36,"Dolan, Linda",1.101024e+09,MA,2119.0,1988-07-18,29.0,Female,Married,US Citizen,No,...,NaT,N/A - still employed,Active,IT/IS,Network Engineer,37.00,Peter Monroe,Employee Referral,90-day meets,76960.0
37,"Gonzalez, Maria",1.988300e+09,MA,2472.0,1981-04-16,36.0,Female,Separated,US Citizen,Yes,...,NaT,N/A - still employed,Active,IT/IS,Network Engineer,39.00,Peter Monroe,Employee Referral,Fully Meets,81120.0
38,"Merlos, Carlos",1.012023e+09,MA,2138.0,1987-06-18,30.0,Male,Single,US Citizen,No,...,NaT,N/A - still employed,Active,IT/IS,Network Engineer,43.00,Peter Monroe,Vendor Referral,N/A- too early to review,89440.0
39,"Morway, Tanya",1.001957e+09,MA,2048.0,1979-04-04,38.0,Female,Married,US Citizen,No,...,NaT,N/A - still employed,Active,IT/IS,Network Engineer,27.00,Peter Monroe,Monster.com,Fully Meets,56160.0
40,"Shepard, Anita",9.060142e+08,MA,1773.0,1981-04-14,36.0,Female,Married,US Citizen,No,...,NaT,N/A - still employed,Active,IT/IS,Network Engineer,47.00,Peter Monroe,Vendor Referral,Fully Meets,97760.0
41,"Tredinnick, Neville",1.104025e+09,MA,1420.0,1988-05-05,29.0,Male,Married,US Citizen,No,...,2015-05-12,medical issues,Voluntarily Terminated,IT/IS,Network Engineer,28.00,Peter Monroe,Monster.com,Fully Meets,58240.0
42,"Turpin, Jumil",1.411072e+09,MA,2343.0,1969-03-31,48.0,Male,Married,Eligible NonCitizen,No,...,NaT,N/A - still employed,Active,IT/IS,Network Engineer,49.10,Peter Monroe,Employee Referral,N/A- too early to review,102128.0
43,"Ait Sidi, Karthikeyan",1.307060e+09,MA,2148.0,1975-05-05,42.0,Male,Married,US Citizen,No,...,2016-06-16,career change,Voluntarily Terminated,IT/IS,Sr. DBA,62.00,Simon Roup,Company Intranet - Partner,Fully Meets,128960.0
44,"Carr, Claudia N",1.010022e+09,MA,1886.0,1986-06-06,31.0,Female,Single,US Citizen,No,...,NaT,N/A - Has not started yet,Future Start,IT/IS,Sr. DBA,61.30,Simon Roup,Vendor Referral,N/A- too early to review,127504.0
45,"Favis, Donald",1.412072e+09,CT,6033.0,1964-07-30,53.0,Male,Single,US Citizen,No,...,2016-02-19,hours,Terminated for Cause,IT/IS,Sr. DBA,58.20,Simon Roup,Vendor Referral,Fully Meets,121056.0
46,"Roehrich, Bianca",1.111030e+09,MA,2703.0,1973-05-27,44.0,Female,Single,US Citizen,Yes,...,2015-11-10,Another position,Voluntarily Terminated,IT/IS,Sr. DBA,58.50,Simon Roup,Vendor Referral,90-day meets,121680.0
47,"Daniele, Ann",1.411071e+09,CT,6033.0,1952-01-18,66.0,Female,Married,US Citizen,No,...,NaT,N/A - still employed,Leave of Absence,IT/IS,Sr. Network Engineer,54.10,Peter Monroe,Vendor Referral,Fully Meets,112528.0
48,"Lajiri, Jyoti",1.108028e+09,MA,2169.0,1986-04-23,31.0,Male,Married,US Citizen,No,...,NaT,N/A - still employed,Leave of Absence,IT/IS,Sr. Network Engineer,56.20,Peter Monroe,Employee Referral,Fully Meets,116896.0
49,"Semizoglou, Jeremiah",9.040136e+08,MA,1545.0,1983-02-09,34.0,Male,Married,US Citizen,No,...,NaT,N/A - Has not started yet,Future Start,IT/IS,Sr. Network Engineer,53.80,Peter Monroe,On-campus Recruiting,N/A- too early to review,111904.0
50,"South, Joe",1.308061e+09,CT,6278.0,1965-09-09,52.0,Male,Single,US Citizen,No,...,NaT,N/A - still employed,Active,IT/IS,Sr. Network Engineer,53.00,Peter Monroe,Employee Referral,90-day meets,110240.0
51,"Warfield, Sarah",1.301052e+09,MA,2453.0,1978-05-02,39.0,Female,Widowed,US Citizen,No,...,NaT,N/A - still employed,Active,IT/IS,Sr. Network Engineer,55.20,Peter Monroe,Employee Referral,N/A- too early to review,114816.0
52,"Bramante, Elisa",1.006020e+09,MA,2030.0,1983-03-19,34.0,Female,Single,US Citizen,No,...,NaT,N/A - still employed,Active,Production,Director of Operations,60.00,Janet King,Other,Exceeds,124800.0

In [16]:
df.dtypes

EmployeeName                 object
EmployeeID                  float64
State                        object
ZipCode                     float64
DOB                  datetime64[ns]
Age                         float64
Sex                          object
MaritalDesc                  object
CitizenDesc                  object
HispanicLatino               object
RaceDesc                     object
DateofHire           datetime64[ns]
DateofTermination    datetime64[ns]
ReasonForTerm                object
EmploymentStatus             object
Department                   object
Position                     object
PayRate                     float64
ManagerName                  object
EmployeeSource               object
PerformanceScore             object
Salary                      float64
dtype: object

In [17]:
df.head(273)

,EmployeeName,EmployeeID,State,ZipCode,DOB,Age,Sex,MaritalDesc,CitizenDesc,HispanicLatino,...,DateofTermination,ReasonForTerm,EmploymentStatus,Department,Position,PayRate,ManagerName,EmployeeSource,PerformanceScore,Salary
0,"Brown, Mia",1.103024e+09,MA,1450.0,1985-11-24,32.0,Female,Married,US Citizen,No,...,NaT,N/A - still employed,Active,Admin Offices,Accountant I,28.50,Brandon R. LeBlanc,Diversity Job Fair,Fully Meets,59280.0
1,"LaRotonda, William",1.106027e+09,MA,1460.0,1984-04-26,33.0,Male,Divorced,US Citizen,No,...,NaT,N/A - still employed,Active,Admin Offices,Accountant I,23.00,Brandon R. LeBlanc,Website Banner Ads,Fully Meets,47840.0
2,"Steans, Tyrone",1.302053e+09,MA,2703.0,1986-09-01,31.0,Male,Single,US Citizen,No,...,NaT,N/A - still employed,Active,Admin Offices,Accountant I,29.00,Brandon R. LeBlanc,Internet Search,Fully Meets,60320.0
3,"Howard, Estelle",1.211051e+09,MA,2170.0,1985-09-16,32.0,Female,Married,US Citizen,No,...,2015-04-15,N/A - still employed,Active,Admin Offices,Administrative Assistant,21.50,Brandon R. LeBlanc,Pay Per Click - Google,N/A- too early to review,44720.0
4,"Singh, Nan",1.307060e+09,MA,2330.0,1988-05-19,29.0,Female,Single,US Citizen,No,...,NaT,N/A - still employed,Active,Admin Offices,Administrative Assistant,16.56,Brandon R. LeBlanc,Website Banner Ads,N/A- too early to review,34444.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
268,"Gill, Whitney",1.302053e+09,OH,43050.0,1971-07-10,46.0,Female,Widowed,US Citizen,No,...,2015-09-05,attendance,Terminated for Cause,Sales,Area Sales Manager,55.00,John Smith,Monster.com,Fully Meets,114400.0
269,"Givens, Myriam",1.203032e+09,IN,46204.0,1989-09-22,28.0,Female,Single,US Citizen,No,...,NaT,N/A - still employed,Active,Sales,Area Sales Manager,55.00,Lynn Daneault,Pay Per Click - Google,90-day meets,114400.0
270,"Gonzales, Ricardo",1.411071e+09,ID,83706.0,1954-10-12,63.0,Male,Married,US Citizen,No,...,NaT,N/A - still employed,Active,Sales,Area Sales Manager,55.50,John Smith,Monster.com,Fully Meets,115440.0
271,"Guilianno, Mike",1.001167e+09,TN,37129.0,1969-02-09,48.0,Male,Single,US Citizen,No,...,2014-10-31,relocation out of area,Voluntarily Terminated,Sales,Area Sales Manager,55.00,John Smith,Newspager/Magazine,Fully Meets,114400.0
272,Jeremy Prater,1.001085e+09,NV,89139.0,1974-05-09,43.0,Male,Married,US Citizen,No,...,NaT,N/A - still employed,Active,Sales,Area Sales Manager,56.00,Lynn Daneault,Website Banner Ads,PIP,116480.0

In [18]:
df.iloc[272,0] = "Jeremy, Prater"

In [19]:
df.head(273)

,EmployeeName,EmployeeID,State,ZipCode,DOB,Age,Sex,MaritalDesc,CitizenDesc,HispanicLatino,...,DateofTermination,ReasonForTerm,EmploymentStatus,Department,Position,PayRate,ManagerName,EmployeeSource,PerformanceScore,Salary
0,"Brown, Mia",1.103024e+09,MA,1450.0,1985-11-24,32.0,Female,Married,US Citizen,No,...,NaT,N/A - still employed,Active,Admin Offices,Accountant I,28.50,Brandon R. LeBlanc,Diversity Job Fair,Fully Meets,59280.0
1,"LaRotonda, William",1.106027e+09,MA,1460.0,1984-04-26,33.0,Male,Divorced,US Citizen,No,...,NaT,N/A - still employed,Active,Admin Offices,Accountant I,23.00,Brandon R. LeBlanc,Website Banner Ads,Fully Meets,47840.0
2,"Steans, Tyrone",1.302053e+09,MA,2703.0,1986-09-01,31.0,Male,Single,US Citizen,No,...,NaT,N/A - still employed,Active,Admin Offices,Accountant I,29.00,Brandon R. LeBlanc,Internet Search,Fully Meets,60320.0
3,"Howard, Estelle",1.211051e+09,MA,2170.0,1985-09-16,32.0,Female,Married,US Citizen,No,...,2015-04-15,N/A - still employed,Active,Admin Offices,Administrative Assistant,21.50,Brandon R. LeBlanc,Pay Per Click - Google,N/A- too early to review,44720.0
4,"Singh, Nan",1.307060e+09,MA,2330.0,1988-05-19,29.0,Female,Single,US Citizen,No,...,NaT,N/A - still employed,Active,Admin Offices,Administrative Assistant,16.56,Brandon R. LeBlanc,Website Banner Ads,N/A- too early to review,34444.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
268,"Gill, Whitney",1.302053e+09,OH,43050.0,1971-07-10,46.0,Female,Widowed,US Citizen,No,...,2015-09-05,attendance,Terminated for Cause,Sales,Area Sales Manager,55.00,John Smith,Monster.com,Fully Meets,114400.0
269,"Givens, Myriam",1.203032e+09,IN,46204.0,1989-09-22,28.0,Female,Single,US Citizen,No,...,NaT,N/A - still employed,Active,Sales,Area Sales Manager,55.00,Lynn Daneault,Pay Per Click - Google,90-day meets,114400.0
270,"Gonzales, Ricardo",1.411071e+09,ID,83706.0,1954-10-12,63.0,Male,Married,US Citizen,No,...,NaT,N/A - still employed,Active,Sales,Area Sales Manager,55.50,John Smith,Monster.com,Fully Meets,115440.0
271,"Guilianno, Mike",1.001167e+09,TN,37129.0,1969-02-09,48.0,Male,Single,US Citizen,No,...,2014-10-31,relocation out of area,Voluntarily Terminated,Sales,Area Sales Manager,55.00,John Smith,Newspager/Magazine,Fully Meets,114400.0
272,"Jeremy, Prater",1.001085e+09,NV,89139.0,1974-05-09,43.0,Male,Married,US Citizen,No,...,NaT,N/A - still employed,Active,Sales,Area Sales Manager,56.00,Lynn Daneault,Website Banner Ads,PIP,116480.0

In [20]:
def split_name(Name):
    splitval = str(Name).split(',')
    last_name, first_name = splitval[0], splitval[1]
    return [last_name, first_name]

In [21]:
df['EmployeeLastName'], df['EmployeeFirstName'] = zip(*df.apply(lambda x: split_name(x['EmployeeName']), axis=1))

In [22]:
df

,EmployeeName,EmployeeID,State,ZipCode,DOB,Age,Sex,MaritalDesc,CitizenDesc,HispanicLatino,...,EmploymentStatus,Department,Position,PayRate,ManagerName,EmployeeSource,PerformanceScore,Salary,EmployeeLastName,EmployeeFirstName
0,"Brown, Mia",1.103024e+09,MA,1450.0,1985-11-24,32.0,Female,Married,US Citizen,No,...,Active,Admin Offices,Accountant I,28.50,Brandon R. LeBlanc,Diversity Job Fair,Fully Meets,59280.0,Brown,Mia
1,"LaRotonda, William",1.106027e+09,MA,1460.0,1984-04-26,33.0,Male,Divorced,US Citizen,No,...,Active,Admin Offices,Accountant I,23.00,Brandon R. LeBlanc,Website Banner Ads,Fully Meets,47840.0,LaRotonda,William
2,"Steans, Tyrone",1.302053e+09,MA,2703.0,1986-09-01,31.0,Male,Single,US Citizen,No,...,Active,Admin Offices,Accountant I,29.00,Brandon R. LeBlanc,Internet Search,Fully Meets,60320.0,Steans,Tyrone
3,"Howard, Estelle",1.211051e+09,MA,2170.0,1985-09-16,32.0,Female,Married,US Citizen,No,...,Active,Admin Offices,Administrative Assistant,21.50,Brandon R. LeBlanc,Pay Per Click - Google,N/A- too early to review,44720.0,Howard,Estelle
4,"Singh, Nan",1.307060e+09,MA,2330.0,1988-05-19,29.0,Female,Single,US Citizen,No,...,Active,Admin Offices,Administrative Assistant,16.56,Brandon R. LeBlanc,Website Banner Ads,N/A- too early to review,34444.8,Singh,Nan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
296,"Patronick, Luke",1.112031e+09,MA,1844.0,1979-02-20,38.0,Male,Single,US Citizen,No,...,Voluntarily Terminated,Software Engineering,Software Engineer,52.25,Alex Sweetwater,Diversity Job Fair,Exceeds,108680.0,Patronick,Luke
297,"Saada, Adell",1.012023e+09,MA,2132.0,1986-07-24,31.0,Female,Married,US Citizen,No,...,Active,Software Engineering,Software Engineer,49.25,Alex Sweetwater,Pay Per Click - Google,Fully Meets,102440.0,Saada,Adell
298,"Szabo, Andrew",1.201031e+09,MA,2140.0,1983-05-06,34.0,Male,Single,US Citizen,No,...,Active,Software Engineering,Software Engineer,48.00,Alex Sweetwater,MBTA ads,Exceptional,99840.0,Szabo,Andrew
299,"True, Edward",1.102024e+09,MA,2451.0,1983-06-14,34.0,Male,Single,Non-Citizen,No,...,Voluntarily Terminated,Software Engineering,Software Engineer,45.42,Alex Sweetwater,Diversity Job Fair,Fully Meets,94473.6,True,Edward
300,"Sweetwater, Alex",1.001645e+09,MA,2184.0,1966-11-22,51.0,Male,Single,US Citizen,No,...,Active,Software Engineering,Software Engineering Manager,27.00,Jennifer Zamora,Search Engine - Google Bing Yahoo,Fully Meets,56160.0,Sweetwater,Alex

In [23]:
df.drop('EmployeeName', axis = 1, inplace = True)

In [24]:
df

,EmployeeID,State,ZipCode,DOB,Age,Sex,MaritalDesc,CitizenDesc,HispanicLatino,RaceDesc,...,EmploymentStatus,Department,Position,PayRate,ManagerName,EmployeeSource,PerformanceScore,Salary,EmployeeLastName,EmployeeFirstName
0,1.103024e+09,MA,1450.0,1985-11-24,32.0,Female,Married,US Citizen,No,Black or African American,...,Active,Admin Offices,Accountant I,28.50,Brandon R. LeBlanc,Diversity Job Fair,Fully Meets,59280.0,Brown,Mia
1,1.106027e+09,MA,1460.0,1984-04-26,33.0,Male,Divorced,US Citizen,No,Black or African American,...,Active,Admin Offices,Accountant I,23.00,Brandon R. LeBlanc,Website Banner Ads,Fully Meets,47840.0,LaRotonda,William
2,1.302053e+09,MA,2703.0,1986-09-01,31.0,Male,Single,US Citizen,No,White,...,Active,Admin Offices,Accountant I,29.00,Brandon R. LeBlanc,Internet Search,Fully Meets,60320.0,Steans,Tyrone
3,1.211051e+09,MA,2170.0,1985-09-16,32.0,Female,Married,US Citizen,No,White,...,Active,Admin Offices,Administrative Assistant,21.50,Brandon R. LeBlanc,Pay Per Click - Google,N/A- too early to review,44720.0,Howard,Estelle
4,1.307060e+09,MA,2330.0,1988-05-19,29.0,Female,Single,US Citizen,No,White,...,Active,Admin Offices,Administrative Assistant,16.56,Brandon R. LeBlanc,Website Banner Ads,N/A- too early to review,34444.8,Singh,Nan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
296,1.112031e+09,MA,1844.0,1979-02-20,38.0,Male,Single,US Citizen,No,Asian,...,Voluntarily Terminated,Software Engineering,Software Engineer,52.25,Alex Sweetwater,Diversity Job Fair,Exceeds,108680.0,Patronick,Luke
297,1.012023e+09,MA,2132.0,1986-07-24,31.0,Female,Married,US Citizen,No,White,...,Active,Software Engineering,Software Engineer,49.25,Alex Sweetwater,Pay Per Click - Google,Fully Meets,102440.0,Saada,Adell
298,1.201031e+09,MA,2140.0,1983-05-06,34.0,Male,Single,US Citizen,No,White,...,Active,Software Engineering,Software Engineer,48.00,Alex Sweetwater,MBTA ads,Exceptional,99840.0,Szabo,Andrew
299,1.102024e+09,MA,2451.0,1983-06-14,34.0,Male,Single,Non-Citizen,No,Black or African American,...,Voluntarily Terminated,Software Engineering,Software Engineer,45.42,Alex Sweetwater,Diversity Job Fair,Fully Meets,94473.6,True,Edward
300,1.001645e+09,MA,2184.0,1966-11-22,51.0,Male,Single,US Citizen,No,White,...,Active,Software Engineering,Software Engineering Manager,27.00,Jennifer Zamora,Search Engine - Google Bing Yahoo,Fully Meets,56160.0,Sweetwater,Alex

In [31]:
df.iloc[16,13]

'Leave of Absence'

In [ ]:
df.to_csv(r'C:\Users\Ron\Documents\core_dataset2.csv')