In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('C:/Users/Ron/Documents/HRDataset_v13.csv')

In [3]:
df.head()

,Employee_Name,EmpID,MarriedID,MaritalStatusID,GenderID,EmpStatusID,DeptID,PerfScoreID,FromDiversityJobFairID,PayRate,...,Department,ManagerName,ManagerID,RecruitmentSource,PerformanceScore,EngagementSurvey,EmpSatisfaction,SpecialProjectsCount,LastPerformanceReview_Date,DaysLateLast30
0,"Brown, Mia",1.103024e+09,1.0,1.0,0.0,1.0,1.0,3.0,1.0,28.50,...,Admin Offices,Brandon R. LeBlanc,1.0,Diversity Job Fair,Fully Meets,2.04,2.0,6.0,1/15/2019,0.0
1,"LaRotonda, William",1.106027e+09,0.0,2.0,1.0,1.0,1.0,3.0,0.0,23.00,...,Admin Offices,Brandon R. LeBlanc,1.0,Website Banner Ads,Fully Meets,5.00,4.0,4.0,1/17/2019,0.0
2,"Steans, Tyrone",1.302053e+09,0.0,0.0,1.0,1.0,1.0,3.0,0.0,29.00,...,Admin Offices,Brandon R. LeBlanc,1.0,Internet Search,Fully Meets,3.90,5.0,5.0,1/18/2019,0.0
3,"Howard, Estelle",1.211051e+09,1.0,1.0,0.0,1.0,1.0,3.0,0.0,21.50,...,Admin Offices,Brandon R. LeBlanc,1.0,Pay Per Click - Google,Fully Meets,3.24,3.0,4.0,NaN,NaN
4,"Singh, Nan",1.307060e+09,0.0,0.0,0.0,1.0,1.0,3.0,0.0,16.56,...,Admin Offices,Brandon R. LeBlanc,1.0,Website Banner Ads,Fully Meets,5.00,3.0,5.0,1/15/2019,0.0

In [4]:
df.dtypes

Employee_Name                  object
EmpID                         float64
MarriedID                     float64
MaritalStatusID               float64
GenderID                      float64
EmpStatusID                   float64
DeptID                        float64
PerfScoreID                   float64
FromDiversityJobFairID        float64
PayRate                       float64
Termd                         float64
PositionID                    float64
Position                       object
State                          object
Zip                           float64
DOB                            object
Sex                            object
MaritalDesc                    object
CitizenDesc                    object
HispanicLatino                 object
RaceDesc                       object
DateofHire                     object
DateofTermination              object
TermReason                     object
EmploymentStatus               object
Department                     object
ManagerName                    object
ManagerID                     float64
RecruitmentSource              object
PerformanceScore               object
EngagementSurvey              float64
EmpSatisfaction               float64
SpecialProjectsCount          float64
LastPerformanceReview_Date     object
DaysLateLast30                float64
dtype: object

In [5]:
df=df.rename(columns={'Employee_Name': 'EmployeeName', 'EmpID': 'EmployeeID',
                     'TermReason': 'ReasonForTerm', 'Zip': 'ZipCode', 'LastPerformanceReview_Date': 'LastPerformanceReviewDate'})

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 401 entries, 0 to 400
Data columns (total 35 columns):
EmployeeName                 310 non-null object
EmployeeID                   310 non-null float64
MarriedID                    310 non-null float64
MaritalStatusID              310 non-null float64
GenderID                     310 non-null float64
EmpStatusID                  310 non-null float64
DeptID                       310 non-null float64
PerfScoreID                  310 non-null float64
FromDiversityJobFairID       310 non-null float64
PayRate                      310 non-null float64
Termd                        310 non-null float64
PositionID                   310 non-null float64
Position                     310 non-null object
State                        310 non-null object
ZipCode                      310 non-null float64
DOB                          310 non-null object
Sex                          310 non-null object
MaritalDesc                  310 non-null object
CitizenDesc                  310 non-null object
HispanicLatino               310 non-null object
RaceDesc                     310 non-null object
DateofHire                   310 non-null object
DateofTermination            103 non-null object
ReasonForTerm                309 non-null object
EmploymentStatus             310 non-null object
Department                   310 non-null object
ManagerName                  310 non-null object
ManagerID                    302 non-null float64
RecruitmentSource            310 non-null object
PerformanceScore             310 non-null object
EngagementSurvey             310 non-null float64
EmpSatisfaction              310 non-null float64
SpecialProjectsCount         310 non-null float64
LastPerformanceReviewDate    207 non-null object
DaysLateLast30               207 non-null float64
dtypes: float64(17), object(18)
memory usage: 109.8+ KB

In [7]:
df.isnull

<bound method DataFrame.isnull of              EmployeeName    EmployeeID  MarriedID  MaritalStatusID  GenderID  \
0              Brown, Mia  1.103024e+09        1.0              1.0       0.0
1    LaRotonda, William    1.106027e+09        0.0              2.0       1.0
2        Steans, Tyrone    1.302053e+09        0.0              0.0       1.0
3         Howard, Estelle  1.211051e+09        1.0              1.0       0.0
4             Singh, Nan   1.307060e+09        0.0              0.0       0.0
..                    ...           ...        ...              ...       ...
396                   NaN           NaN        NaN              NaN       NaN
397                   NaN           NaN        NaN              NaN       NaN
398                   NaN           NaN        NaN              NaN       NaN
399                   NaN           NaN        NaN              NaN       NaN
400                   NaN           NaN        NaN              NaN       NaN

     EmpStatusID  DeptID  PerfScoreID  FromDiversityJobFairID  PayRate  ...  \
0            1.0     1.0          3.0                     1.0    28.50  ...
1            1.0     1.0          3.0                     0.0    23.00  ...
2            1.0     1.0          3.0                     0.0    29.00  ...
3            1.0     1.0          3.0                     0.0    21.50  ...
4            1.0     1.0          3.0                     0.0    16.56  ...
..           ...     ...          ...                     ...      ...  ...
396          NaN     NaN          NaN                     NaN      NaN  ...
397          NaN     NaN          NaN                     NaN      NaN  ...
398          NaN     NaN          NaN                     NaN      NaN  ...
399          NaN     NaN          NaN                     NaN      NaN  ...
400          NaN     NaN          NaN                     NaN      NaN  ...

        Department         ManagerName ManagerID       RecruitmentSource  \
0    Admin Offices  Brandon R. LeBlanc       1.0      Diversity Job Fair
1    Admin Offices  Brandon R. LeBlanc       1.0      Website Banner Ads
2    Admin Offices  Brandon R. LeBlanc       1.0         Internet Search
3    Admin Offices  Brandon R. LeBlanc       1.0  Pay Per Click - Google
4    Admin Offices  Brandon R. LeBlanc       1.0      Website Banner Ads
..             ...                 ...       ...                     ...
396            NaN                 NaN       NaN                     NaN
397            NaN                 NaN       NaN                     NaN
398            NaN                 NaN       NaN                     NaN
399            NaN                 NaN       NaN                     NaN
400            NaN                 NaN       NaN                     NaN

     PerformanceScore EngagementSurvey EmpSatisfaction SpecialProjectsCount  \
0         Fully Meets             2.04             2.0                  6.0
1         Fully Meets             5.00             4.0                  4.0
2         Fully Meets             3.90             5.0                  5.0
3         Fully Meets             3.24             3.0                  4.0
4         Fully Meets             5.00             3.0                  5.0
..                ...              ...             ...                  ...
396               NaN              NaN             NaN                  NaN
397               NaN              NaN             NaN                  NaN
398               NaN              NaN             NaN                  NaN
399               NaN              NaN             NaN                  NaN
400               NaN              NaN             NaN                  NaN

    LastPerformanceReviewDate DaysLateLast30
0                   1/15/2019            0.0
1                   1/17/2019            0.0
2                   1/18/2019            0.0
3                         NaN            NaN
4                   1/15/2019            0.0
..                        ...            ...
396                       NaN            NaN
397                       NaN            NaN
398                       NaN            NaN
399                       NaN            NaN
400                       NaN            NaN

[401 rows x 35 columns]>

In [8]:
df

,EmployeeName,EmployeeID,MarriedID,MaritalStatusID,GenderID,EmpStatusID,DeptID,PerfScoreID,FromDiversityJobFairID,PayRate,...,Department,ManagerName,ManagerID,RecruitmentSource,PerformanceScore,EngagementSurvey,EmpSatisfaction,SpecialProjectsCount,LastPerformanceReviewDate,DaysLateLast30
0,"Brown, Mia",1.103024e+09,1.0,1.0,0.0,1.0,1.0,3.0,1.0,28.50,...,Admin Offices,Brandon R. LeBlanc,1.0,Diversity Job Fair,Fully Meets,2.04,2.0,6.0,1/15/2019,0.0
1,"LaRotonda, William",1.106027e+09,0.0,2.0,1.0,1.0,1.0,3.0,0.0,23.00,...,Admin Offices,Brandon R. LeBlanc,1.0,Website Banner Ads,Fully Meets,5.00,4.0,4.0,1/17/2019,0.0
2,"Steans, Tyrone",1.302053e+09,0.0,0.0,1.0,1.0,1.0,3.0,0.0,29.00,...,Admin Offices,Brandon R. LeBlanc,1.0,Internet Search,Fully Meets,3.90,5.0,5.0,1/18/2019,0.0
3,"Howard, Estelle",1.211051e+09,1.0,1.0,0.0,1.0,1.0,3.0,0.0,21.50,...,Admin Offices,Brandon R. LeBlanc,1.0,Pay Per Click - Google,Fully Meets,3.24,3.0,4.0,NaN,NaN
4,"Singh, Nan",1.307060e+09,0.0,0.0,0.0,1.0,1.0,3.0,0.0,16.56,...,Admin Offices,Brandon R. LeBlanc,1.0,Website Banner Ads,Fully Meets,5.00,3.0,5.0,1/15/2019,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
396,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
397,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
398,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
399,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
400,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
df2=df.iloc[0:310]

In [10]:
df2

,EmployeeName,EmployeeID,MarriedID,MaritalStatusID,GenderID,EmpStatusID,DeptID,PerfScoreID,FromDiversityJobFairID,PayRate,...,Department,ManagerName,ManagerID,RecruitmentSource,PerformanceScore,EngagementSurvey,EmpSatisfaction,SpecialProjectsCount,LastPerformanceReviewDate,DaysLateLast30
0,"Brown, Mia",1.103024e+09,1.0,1.0,0.0,1.0,1.0,3.0,1.0,28.50,...,Admin Offices,Brandon R. LeBlanc,1.0,Diversity Job Fair,Fully Meets,2.04,2.0,6.0,1/15/2019,0.0
1,"LaRotonda, William",1.106027e+09,0.0,2.0,1.0,1.0,1.0,3.0,0.0,23.00,...,Admin Offices,Brandon R. LeBlanc,1.0,Website Banner Ads,Fully Meets,5.00,4.0,4.0,1/17/2019,0.0
2,"Steans, Tyrone",1.302053e+09,0.0,0.0,1.0,1.0,1.0,3.0,0.0,29.00,...,Admin Offices,Brandon R. LeBlanc,1.0,Internet Search,Fully Meets,3.90,5.0,5.0,1/18/2019,0.0
3,"Howard, Estelle",1.211051e+09,1.0,1.0,0.0,1.0,1.0,3.0,0.0,21.50,...,Admin Offices,Brandon R. LeBlanc,1.0,Pay Per Click - Google,Fully Meets,3.24,3.0,4.0,NaN,NaN
4,"Singh, Nan",1.307060e+09,0.0,0.0,0.0,1.0,1.0,3.0,0.0,16.56,...,Admin Offices,Brandon R. LeBlanc,1.0,Website Banner Ads,Fully Meets,5.00,3.0,5.0,1/15/2019,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
305,"Daniele, Ann",1.411071e+09,1.0,1.0,0.0,3.0,3.0,3.0,0.0,54.10,...,IT/IS,Peter Monroe,7.0,Vendor Referral,Fully Meets,1.55,5.0,8.0,2/12/2019,0.0
306,"Lajiri, Jyoti",1.108028e+09,1.0,1.0,1.0,3.0,3.0,3.0,0.0,56.20,...,IT/IS,Peter Monroe,7.0,Employee Referral,Fully Meets,4.46,5.0,6.0,1/7/2019,0.0
307,"Semizoglou, Jeremiah",9.040136e+08,1.0,1.0,1.0,2.0,3.0,3.0,0.0,53.80,...,IT/IS,Peter Monroe,7.0,On-campus Recruiting,Fully Meets,3.27,4.0,5.0,1/14/2019,0.0
308,"South, Joe",1.308061e+09,0.0,0.0,1.0,1.0,3.0,3.0,0.0,53.00,...,IT/IS,Peter Monroe,7.0,Employee Referral,Fully Meets,5.00,3.0,4.0,1/2/2019,0.0
309,"Warfield, Sarah",1.301052e+09,0.0,4.0,0.0,1.0,3.0,3.0,0.0,55.20,...,IT/IS,Peter Monroe,7.0,Employee Referral,Fully Meets,1.06,4.0,8.0,2/5/2019,0.0

In [11]:
df2['DateofHire'] = pd.to_datetime(df2['DateofHire'])

C:\Users\Ron\Anaconda3\envs\dsi04\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [13]:
df2['LastPerformanceReviewDate'] = pd.to_datetime(df2['LastPerformanceReviewDate'])

C:\Users\Ron\Anaconda3\envs\dsi04\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [14]:
df2['DOB'] = pd.to_datetime(df2['DOB'])

C:\Users\Ron\Anaconda3\envs\dsi04\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [15]:
df2['DateofTermination'] = pd.to_datetime(df2['DateofTermination'])

C:\Users\Ron\Anaconda3\envs\dsi04\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [16]:
df2.dtypes

EmployeeName                         object
EmployeeID                          float64
MarriedID                           float64
MaritalStatusID                     float64
GenderID                            float64
EmpStatusID                         float64
DeptID                              float64
PerfScoreID                         float64
FromDiversityJobFairID              float64
PayRate                             float64
Termd                               float64
PositionID                          float64
Position                             object
State                                object
ZipCode                             float64
DOB                          datetime64[ns]
Sex                                  object
MaritalDesc                          object
CitizenDesc                          object
HispanicLatino                       object
RaceDesc                             object
DateofHire                   datetime64[ns]
DateofTermination            datetime64[ns]
ReasonForTerm                        object
EmploymentStatus                     object
Department                           object
ManagerName                          object
ManagerID                           float64
RecruitmentSource                    object
PerformanceScore                     object
EngagementSurvey                    float64
EmpSatisfaction                     float64
SpecialProjectsCount                float64
LastPerformanceReviewDate    datetime64[ns]
DaysLateLast30                      float64
dtype: object

In [17]:
df2.DOB

0     1987-11-24
1     1984-04-26
2     1986-09-01
3     1985-09-16
4     1988-05-19
         ...
305   2052-01-18
306   1986-04-23
307   1983-02-09
308   2065-09-09
309   1978-05-02
Name: DOB, Length: 310, dtype: datetime64[ns]

In [18]:
df2.DateofHire

0     2008-10-27
1     2014-01-06
2     2014-09-29
3     2015-02-16
4     2015-05-01
         ...
305   2014-11-10
306   2014-11-10
307   2016-06-30
308   2014-11-10
309   2015-03-30
Name: DateofHire, Length: 310, dtype: datetime64[ns]

In [20]:
df2.LastPerformanceReviewDate

0     2019-01-15
1     2019-01-17
2     2019-01-18
3            NaT
4     2019-01-15
         ...
305   2019-02-12
306   2019-01-07
307   2019-01-14
308   2019-01-02
309   2019-02-05
Name: LastPerformanceReviewDate, Length: 310, dtype: datetime64[ns]

In [21]:
df2.DateofTermination

0            NaT
1            NaT
2            NaT
3     2015-04-15
4            NaT
         ...
305          NaT
306          NaT
307          NaT
308          NaT
309          NaT
Name: DateofTermination, Length: 310, dtype: datetime64[ns]

In [22]:
df2.drop('DaysLateLast30', axis=1)

,EmployeeName,EmployeeID,MarriedID,MaritalStatusID,GenderID,EmpStatusID,DeptID,PerfScoreID,FromDiversityJobFairID,PayRate,...,EmploymentStatus,Department,ManagerName,ManagerID,RecruitmentSource,PerformanceScore,EngagementSurvey,EmpSatisfaction,SpecialProjectsCount,LastPerformanceReviewDate
0,"Brown, Mia",1.103024e+09,1.0,1.0,0.0,1.0,1.0,3.0,1.0,28.50,...,Active,Admin Offices,Brandon R. LeBlanc,1.0,Diversity Job Fair,Fully Meets,2.04,2.0,6.0,2019-01-15
1,"LaRotonda, William",1.106027e+09,0.0,2.0,1.0,1.0,1.0,3.0,0.0,23.00,...,Active,Admin Offices,Brandon R. LeBlanc,1.0,Website Banner Ads,Fully Meets,5.00,4.0,4.0,2019-01-17
2,"Steans, Tyrone",1.302053e+09,0.0,0.0,1.0,1.0,1.0,3.0,0.0,29.00,...,Active,Admin Offices,Brandon R. LeBlanc,1.0,Internet Search,Fully Meets,3.90,5.0,5.0,2019-01-18
3,"Howard, Estelle",1.211051e+09,1.0,1.0,0.0,1.0,1.0,3.0,0.0,21.50,...,Terminated for Cause,Admin Offices,Brandon R. LeBlanc,1.0,Pay Per Click - Google,Fully Meets,3.24,3.0,4.0,NaT
4,"Singh, Nan",1.307060e+09,0.0,0.0,0.0,1.0,1.0,3.0,0.0,16.56,...,Active,Admin Offices,Brandon R. LeBlanc,1.0,Website Banner Ads,Fully Meets,5.00,3.0,5.0,2019-01-15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
305,"Daniele, Ann",1.411071e+09,1.0,1.0,0.0,3.0,3.0,3.0,0.0,54.10,...,Leave of Absence,IT/IS,Peter Monroe,7.0,Vendor Referral,Fully Meets,1.55,5.0,8.0,2019-02-12
306,"Lajiri, Jyoti",1.108028e+09,1.0,1.0,1.0,3.0,3.0,3.0,0.0,56.20,...,Leave of Absence,IT/IS,Peter Monroe,7.0,Employee Referral,Fully Meets,4.46,5.0,6.0,2019-01-07
307,"Semizoglou, Jeremiah",9.040136e+08,1.0,1.0,1.0,2.0,3.0,3.0,0.0,53.80,...,Future Start,IT/IS,Peter Monroe,7.0,On-campus Recruiting,Fully Meets,3.27,4.0,5.0,2019-01-14
308,"South, Joe",1.308061e+09,0.0,0.0,1.0,1.0,3.0,3.0,0.0,53.00,...,Active,IT/IS,Peter Monroe,7.0,Employee Referral,Fully Meets,5.00,3.0,4.0,2019-01-02
309,"Warfield, Sarah",1.301052e+09,0.0,4.0,0.0,1.0,3.0,3.0,0.0,55.20,...,Active,IT/IS,Peter Monroe,7.0,Employee Referral,Fully Meets,1.06,4.0,8.0,2019-02-05

In [23]:
df2['Salary'] = df2.PayRate*40*52

C:\Users\Ron\Anaconda3\envs\dsi04\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [24]:
df2.head()

,EmployeeName,EmployeeID,MarriedID,MaritalStatusID,GenderID,EmpStatusID,DeptID,PerfScoreID,FromDiversityJobFairID,PayRate,...,ManagerName,ManagerID,RecruitmentSource,PerformanceScore,EngagementSurvey,EmpSatisfaction,SpecialProjectsCount,LastPerformanceReviewDate,DaysLateLast30,Salary
0,"Brown, Mia",1.103024e+09,1.0,1.0,0.0,1.0,1.0,3.0,1.0,28.50,...,Brandon R. LeBlanc,1.0,Diversity Job Fair,Fully Meets,2.04,2.0,6.0,2019-01-15,0.0,59280.0
1,"LaRotonda, William",1.106027e+09,0.0,2.0,1.0,1.0,1.0,3.0,0.0,23.00,...,Brandon R. LeBlanc,1.0,Website Banner Ads,Fully Meets,5.00,4.0,4.0,2019-01-17,0.0,47840.0
2,"Steans, Tyrone",1.302053e+09,0.0,0.0,1.0,1.0,1.0,3.0,0.0,29.00,...,Brandon R. LeBlanc,1.0,Internet Search,Fully Meets,3.90,5.0,5.0,2019-01-18,0.0,60320.0
3,"Howard, Estelle",1.211051e+09,1.0,1.0,0.0,1.0,1.0,3.0,0.0,21.50,...,Brandon R. LeBlanc,1.0,Pay Per Click - Google,Fully Meets,3.24,3.0,4.0,NaT,NaN,44720.0
4,"Singh, Nan",1.307060e+09,0.0,0.0,0.0,1.0,1.0,3.0,0.0,16.56,...,Brandon R. LeBlanc,1.0,Website Banner Ads,Fully Meets,5.00,3.0,5.0,2019-01-15,0.0,34444.8

In [25]:
df2.drop('DaysLateLast30', axis=1, inplace=True)

C:\Users\Ron\Anaconda3\envs\dsi04\lib\site-packages\pandas\core\frame.py:4102: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

In [26]:
df2.head()

,EmployeeName,EmployeeID,MarriedID,MaritalStatusID,GenderID,EmpStatusID,DeptID,PerfScoreID,FromDiversityJobFairID,PayRate,...,Department,ManagerName,ManagerID,RecruitmentSource,PerformanceScore,EngagementSurvey,EmpSatisfaction,SpecialProjectsCount,LastPerformanceReviewDate,Salary
0,"Brown, Mia",1.103024e+09,1.0,1.0,0.0,1.0,1.0,3.0,1.0,28.50,...,Admin Offices,Brandon R. LeBlanc,1.0,Diversity Job Fair,Fully Meets,2.04,2.0,6.0,2019-01-15,59280.0
1,"LaRotonda, William",1.106027e+09,0.0,2.0,1.0,1.0,1.0,3.0,0.0,23.00,...,Admin Offices,Brandon R. LeBlanc,1.0,Website Banner Ads,Fully Meets,5.00,4.0,4.0,2019-01-17,47840.0
2,"Steans, Tyrone",1.302053e+09,0.0,0.0,1.0,1.0,1.0,3.0,0.0,29.00,...,Admin Offices,Brandon R. LeBlanc,1.0,Internet Search,Fully Meets,3.90,5.0,5.0,2019-01-18,60320.0
3,"Howard, Estelle",1.211051e+09,1.0,1.0,0.0,1.0,1.0,3.0,0.0,21.50,...,Admin Offices,Brandon R. LeBlanc,1.0,Pay Per Click - Google,Fully Meets,3.24,3.0,4.0,NaT,44720.0
4,"Singh, Nan",1.307060e+09,0.0,0.0,0.0,1.0,1.0,3.0,0.0,16.56,...,Admin Offices,Brandon R. LeBlanc,1.0,Website Banner Ads,Fully Meets,5.00,3.0,5.0,2019-01-15,34444.8

In [27]:
df2.dtypes

EmployeeName                         object
EmployeeID                          float64
MarriedID                           float64
MaritalStatusID                     float64
GenderID                            float64
EmpStatusID                         float64
DeptID                              float64
PerfScoreID                         float64
FromDiversityJobFairID              float64
PayRate                             float64
Termd                               float64
PositionID                          float64
Position                             object
State                                object
ZipCode                             float64
DOB                          datetime64[ns]
Sex                                  object
MaritalDesc                          object
CitizenDesc                          object
HispanicLatino                       object
RaceDesc                             object
DateofHire                   datetime64[ns]
DateofTermination            datetime64[ns]
ReasonForTerm                        object
EmploymentStatus                     object
Department                           object
ManagerName                          object
ManagerID                           float64
RecruitmentSource                    object
PerformanceScore                     object
EngagementSurvey                    float64
EmpSatisfaction                     float64
SpecialProjectsCount                float64
LastPerformanceReviewDate    datetime64[ns]
Salary                              float64
dtype: object

In [28]:
df2.head(273)

,EmployeeName,EmployeeID,MarriedID,MaritalStatusID,GenderID,EmpStatusID,DeptID,PerfScoreID,FromDiversityJobFairID,PayRate,...,Department,ManagerName,ManagerID,RecruitmentSource,PerformanceScore,EngagementSurvey,EmpSatisfaction,SpecialProjectsCount,LastPerformanceReviewDate,Salary
0,"Brown, Mia",1.103024e+09,1.0,1.0,0.0,1.0,1.0,3.0,1.0,28.50,...,Admin Offices,Brandon R. LeBlanc,1.0,Diversity Job Fair,Fully Meets,2.04,2.0,6.0,2019-01-15,59280.0
1,"LaRotonda, William",1.106027e+09,0.0,2.0,1.0,1.0,1.0,3.0,0.0,23.00,...,Admin Offices,Brandon R. LeBlanc,1.0,Website Banner Ads,Fully Meets,5.00,4.0,4.0,2019-01-17,47840.0
2,"Steans, Tyrone",1.302053e+09,0.0,0.0,1.0,1.0,1.0,3.0,0.0,29.00,...,Admin Offices,Brandon R. LeBlanc,1.0,Internet Search,Fully Meets,3.90,5.0,5.0,2019-01-18,60320.0
3,"Howard, Estelle",1.211051e+09,1.0,1.0,0.0,1.0,1.0,3.0,0.0,21.50,...,Admin Offices,Brandon R. LeBlanc,1.0,Pay Per Click - Google,Fully Meets,3.24,3.0,4.0,NaT,44720.0
4,"Singh, Nan",1.307060e+09,0.0,0.0,0.0,1.0,1.0,3.0,0.0,16.56,...,Admin Offices,Brandon R. LeBlanc,1.0,Website Banner Ads,Fully Meets,5.00,3.0,5.0,2019-01-15,34444.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
268,"Woodson, Jason",1.012023e+09,0.0,0.0,1.0,1.0,5.0,3.0,0.0,24.25,...,Production,Kissy Sullivan,20.0,Vendor Referral,Fully Meets,4.07,4.0,0.0,2019-02-28,50440.0
269,"Blount, Dianna",1.403066e+09,0.0,0.0,0.0,1.0,5.0,2.0,0.0,27.00,...,Production,Michael Albert,22.0,Monster.com,Needs Improvement,1.16,3.0,0.0,2019-02-27,56160.0
270,"Erilus, Angela",1.105026e+09,0.0,3.0,0.0,1.0,5.0,1.0,0.0,24.00,...,Production,Michael Albert,22.0,Pay Per Click - Google,PIP,4.59,1.0,0.0,2019-02-25,49920.0
271,"Homberger, Adrienne J",1.207047e+09,1.0,1.0,0.0,5.0,5.0,3.0,0.0,28.00,...,Production,Michael Albert,30.0,Glassdoor,Fully Meets,3.03,5.0,0.0,NaT,58240.0
272,"Lundy, Susan",1.305056e+09,0.0,4.0,0.0,5.0,5.0,3.0,0.0,24.00,...,Production,Michael Albert,22.0,On-campus Recruiting,Fully Meets,4.65,4.0,0.0,NaT,49920.0

In [29]:
df2.head(25)

,EmployeeName,EmployeeID,MarriedID,MaritalStatusID,GenderID,EmpStatusID,DeptID,PerfScoreID,FromDiversityJobFairID,PayRate,...,Department,ManagerName,ManagerID,RecruitmentSource,PerformanceScore,EngagementSurvey,EmpSatisfaction,SpecialProjectsCount,LastPerformanceReviewDate,Salary
0,"Brown, Mia",1.103024e+09,1.0,1.0,0.0,1.0,1.0,3.0,1.0,28.50,...,Admin Offices,Brandon R. LeBlanc,1.0,Diversity Job Fair,Fully Meets,2.04,2.0,6.0,2019-01-15,59280.0
1,"LaRotonda, William",1.106027e+09,0.0,2.0,1.0,1.0,1.0,3.0,0.0,23.00,...,Admin Offices,Brandon R. LeBlanc,1.0,Website Banner Ads,Fully Meets,5.00,4.0,4.0,2019-01-17,47840.0
2,"Steans, Tyrone",1.302053e+09,0.0,0.0,1.0,1.0,1.0,3.0,0.0,29.00,...,Admin Offices,Brandon R. LeBlanc,1.0,Internet Search,Fully Meets,3.90,5.0,5.0,2019-01-18,60320.0
3,"Howard, Estelle",1.211051e+09,1.0,1.0,0.0,1.0,1.0,3.0,0.0,21.50,...,Admin Offices,Brandon R. LeBlanc,1.0,Pay Per Click - Google,Fully Meets,3.24,3.0,4.0,NaT,44720.0
4,"Singh, Nan",1.307060e+09,0.0,0.0,0.0,1.0,1.0,3.0,0.0,16.56,...,Admin Offices,Brandon R. LeBlanc,1.0,Website Banner Ads,Fully Meets,5.00,3.0,5.0,2019-01-15,34444.8
5,"Smith, Leigh Ann",7.110077e+08,1.0,1.0,0.0,5.0,1.0,3.0,1.0,20.50,...,Admin Offices,Brandon R. LeBlanc,1.0,Diversity Job Fair,Fully Meets,3.80,4.0,4.0,NaT,42640.0
6,"Bunbury, Jessica",1.504073e+09,1.0,1.0,0.0,5.0,6.0,3.0,0.0,55.00,...,Sales,John Smith,17.0,Social Networks - Facebook Twitter etc,Fully Meets,3.14,5.0,0.0,NaT,114400.0
7,"Carter, Michelle",1.403066e+09,0.0,0.0,0.0,1.0,6.0,3.0,0.0,55.00,...,Sales,John Smith,17.0,Billboard,Fully Meets,5.00,5.0,0.0,2019-01-21,114400.0
8,"Dietrich, Jenna",1.408069e+09,0.0,0.0,0.0,1.0,6.0,1.0,0.0,55.00,...,Sales,John Smith,17.0,Website Banner Ads,PIP,2.30,1.0,0.0,2019-01-29,114400.0
9,"Digitale, Alfred",1.306059e+09,1.0,1.0,1.0,1.0,6.0,3.0,0.0,56.00,...,Sales,John Smith,17.0,Pay Per Click - Google,Fully Meets,3.60,5.0,0.0,2019-01-30,116480.0
10,"Friedman, Gerry",1.204033e+09,0.0,0.0,1.0,1.0,6.0,3.0,1.0,55.50,...,Sales,John Smith,17.0,Diversity Job Fair,Fully Meets,3.65,5.0,0.0,2019-01-17,115440.0
11,"Gill, Whitney",1.302053e+09,0.0,4.0,0.0,4.0,6.0,3.0,0.0,55.00,...,Sales,John Smith,17.0,Monster.com,Fully Meets,3.97,4.0,0.0,NaT,114400.0
12,"Gonzales, Ricardo",1.411071e+09,1.0,1.0,1.0,1.0,6.0,3.0,0.0,55.50,...,Sales,John Smith,17.0,Monster.com,Fully Meets,3.98,3.0,0.0,2019-01-28,115440.0
13,"Guilianno, Mike",1.001167e+09,0.0,0.0,1.0,5.0,6.0,3.0,0.0,55.00,...,Sales,John Smith,17.0,Newspager/Magazine,Fully Meets,4.50,5.0,0.0,NaT,114400.0
14,"Leruth, Giovanni",1.412072e+09,0.0,3.0,1.0,1.0,6.0,3.0,0.0,55.00,...,Sales,John Smith,17.0,Website Banner Ads,Fully Meets,4.53,3.0,0.0,2019-01-29,114400.0
15,"Mullaney, Howard",1.306058e+09,0.0,0.0,1.0,1.0,6.0,1.0,0.0,55.00,...,Sales,John Smith,17.0,Internet Search,PIP,1.93,3.0,0.0,2019-01-30,114400.0
16,"Ozark, Travis",8.120118e+08,0.0,0.0,1.0,1.0,6.0,3.0,0.0,55.00,...,Sales,John Smith,17.0,Website Banner Ads,Fully Meets,5.00,5.0,0.0,2019-01-14,114400.0
17,"Strong, Caitrin",1.411071e+09,1.0,1.0,0.0,1.0,6.0,3.0,0.0,54.00,...,Sales,John Smith,17.0,Professional Society,Fully Meets,2.00,4.0,0.0,2019-01-31,112320.0
18,"Valentin,Jackie",1.312064e+09,1.0,1.0,0.0,1.0,6.0,3.0,0.0,55.00,...,Sales,John Smith,17.0,Other,Fully Meets,2.81,3.0,0.0,2019-01-17,114400.0
19,"Villanueva, Noah",1.111031e+09,0.0,0.0,1.0,1.0,6.0,3.0,0.0,56.00,...,Sales,John Smith,17.0,Website Banner Ads,Fully Meets,1.77,4.0,0.0,2019-01-18,116480.0
20,"Buck, Edward",1.504073e+09,1.0,1.0,1.0,1.0,6.0,3.0,0.0,55.00,...,Sales,Lynn Daneault,21.0,Employee Referral,Fully Meets,3.31,5.0,0.0,2019-01-28,114400.0
21,"Costa, Latia",1.409071e+09,0.0,0.0,0.0,1.0,6.0,4.0,0.0,55.00,...,Sales,Lynn Daneault,21.0,Other,Exceeds,4.77,5.0,0.0,2019-01-27,114400.0
22,"Fraval, Maruk",1.411071e+09,0.0,0.0,1.0,1.0,6.0,3.0,0.0,55.00,...,Sales,Lynn Daneault,21.0,Monster.com,Fully Meets,1.64,3.0,0.0,2019-01-27,114400.0
23,"Givens, Myriam",1.203032e+09,0.0,0.0,0.0,1.0,6.0,3.0,0.0,55.00,...,Sales,Lynn Daneault,21.0,Pay Per Click - Google,Fully Meets,1.72,5.0,0.0,2019-01-25,114400.0
24,Jeremy Prater,1.001085e+09,1.0,1.0,1.0,1.0,6.0,1.0,0.0,56.00,...,Sales,Lynn Daneault,21.0,Website Banner Ads,PIP,1.81,2.0,0.0,2019-01-17,116480.0

In [30]:
df2.iloc[24,0]= "Jeremy,Prater"

C:\Users\Ron\Anaconda3\envs\dsi04\lib\site-packages\pandas\core\indexing.py:494: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[item] = s

In [31]:
df2.head(25)

,EmployeeName,EmployeeID,MarriedID,MaritalStatusID,GenderID,EmpStatusID,DeptID,PerfScoreID,FromDiversityJobFairID,PayRate,...,Department,ManagerName,ManagerID,RecruitmentSource,PerformanceScore,EngagementSurvey,EmpSatisfaction,SpecialProjectsCount,LastPerformanceReviewDate,Salary
0,"Brown, Mia",1.103024e+09,1.0,1.0,0.0,1.0,1.0,3.0,1.0,28.50,...,Admin Offices,Brandon R. LeBlanc,1.0,Diversity Job Fair,Fully Meets,2.04,2.0,6.0,2019-01-15,59280.0
1,"LaRotonda, William",1.106027e+09,0.0,2.0,1.0,1.0,1.0,3.0,0.0,23.00,...,Admin Offices,Brandon R. LeBlanc,1.0,Website Banner Ads,Fully Meets,5.00,4.0,4.0,2019-01-17,47840.0
2,"Steans, Tyrone",1.302053e+09,0.0,0.0,1.0,1.0,1.0,3.0,0.0,29.00,...,Admin Offices,Brandon R. LeBlanc,1.0,Internet Search,Fully Meets,3.90,5.0,5.0,2019-01-18,60320.0
3,"Howard, Estelle",1.211051e+09,1.0,1.0,0.0,1.0,1.0,3.0,0.0,21.50,...,Admin Offices,Brandon R. LeBlanc,1.0,Pay Per Click - Google,Fully Meets,3.24,3.0,4.0,NaT,44720.0
4,"Singh, Nan",1.307060e+09,0.0,0.0,0.0,1.0,1.0,3.0,0.0,16.56,...,Admin Offices,Brandon R. LeBlanc,1.0,Website Banner Ads,Fully Meets,5.00,3.0,5.0,2019-01-15,34444.8
5,"Smith, Leigh Ann",7.110077e+08,1.0,1.0,0.0,5.0,1.0,3.0,1.0,20.50,...,Admin Offices,Brandon R. LeBlanc,1.0,Diversity Job Fair,Fully Meets,3.80,4.0,4.0,NaT,42640.0
6,"Bunbury, Jessica",1.504073e+09,1.0,1.0,0.0,5.0,6.0,3.0,0.0,55.00,...,Sales,John Smith,17.0,Social Networks - Facebook Twitter etc,Fully Meets,3.14,5.0,0.0,NaT,114400.0
7,"Carter, Michelle",1.403066e+09,0.0,0.0,0.0,1.0,6.0,3.0,0.0,55.00,...,Sales,John Smith,17.0,Billboard,Fully Meets,5.00,5.0,0.0,2019-01-21,114400.0
8,"Dietrich, Jenna",1.408069e+09,0.0,0.0,0.0,1.0,6.0,1.0,0.0,55.00,...,Sales,John Smith,17.0,Website Banner Ads,PIP,2.30,1.0,0.0,2019-01-29,114400.0
9,"Digitale, Alfred",1.306059e+09,1.0,1.0,1.0,1.0,6.0,3.0,0.0,56.00,...,Sales,John Smith,17.0,Pay Per Click - Google,Fully Meets,3.60,5.0,0.0,2019-01-30,116480.0
10,"Friedman, Gerry",1.204033e+09,0.0,0.0,1.0,1.0,6.0,3.0,1.0,55.50,...,Sales,John Smith,17.0,Diversity Job Fair,Fully Meets,3.65,5.0,0.0,2019-01-17,115440.0
11,"Gill, Whitney",1.302053e+09,0.0,4.0,0.0,4.0,6.0,3.0,0.0,55.00,...,Sales,John Smith,17.0,Monster.com,Fully Meets,3.97,4.0,0.0,NaT,114400.0
12,"Gonzales, Ricardo",1.411071e+09,1.0,1.0,1.0,1.0,6.0,3.0,0.0,55.50,...,Sales,John Smith,17.0,Monster.com,Fully Meets,3.98,3.0,0.0,2019-01-28,115440.0
13,"Guilianno, Mike",1.001167e+09,0.0,0.0,1.0,5.0,6.0,3.0,0.0,55.00,...,Sales,John Smith,17.0,Newspager/Magazine,Fully Meets,4.50,5.0,0.0,NaT,114400.0
14,"Leruth, Giovanni",1.412072e+09,0.0,3.0,1.0,1.0,6.0,3.0,0.0,55.00,...,Sales,John Smith,17.0,Website Banner Ads,Fully Meets,4.53,3.0,0.0,2019-01-29,114400.0
15,"Mullaney, Howard",1.306058e+09,0.0,0.0,1.0,1.0,6.0,1.0,0.0,55.00,...,Sales,John Smith,17.0,Internet Search,PIP,1.93,3.0,0.0,2019-01-30,114400.0
16,"Ozark, Travis",8.120118e+08,0.0,0.0,1.0,1.0,6.0,3.0,0.0,55.00,...,Sales,John Smith,17.0,Website Banner Ads,Fully Meets,5.00,5.0,0.0,2019-01-14,114400.0
17,"Strong, Caitrin",1.411071e+09,1.0,1.0,0.0,1.0,6.0,3.0,0.0,54.00,...,Sales,John Smith,17.0,Professional Society,Fully Meets,2.00,4.0,0.0,2019-01-31,112320.0
18,"Valentin,Jackie",1.312064e+09,1.0,1.0,0.0,1.0,6.0,3.0,0.0,55.00,...,Sales,John Smith,17.0,Other,Fully Meets,2.81,3.0,0.0,2019-01-17,114400.0
19,"Villanueva, Noah",1.111031e+09,0.0,0.0,1.0,1.0,6.0,3.0,0.0,56.00,...,Sales,John Smith,17.0,Website Banner Ads,Fully Meets,1.77,4.0,0.0,2019-01-18,116480.0
20,"Buck, Edward",1.504073e+09,1.0,1.0,1.0,1.0,6.0,3.0,0.0,55.00,...,Sales,Lynn Daneault,21.0,Employee Referral,Fully Meets,3.31,5.0,0.0,2019-01-28,114400.0
21,"Costa, Latia",1.409071e+09,0.0,0.0,0.0,1.0,6.0,4.0,0.0,55.00,...,Sales,Lynn Daneault,21.0,Other,Exceeds,4.77,5.0,0.0,2019-01-27,114400.0
22,"Fraval, Maruk",1.411071e+09,0.0,0.0,1.0,1.0,6.0,3.0,0.0,55.00,...,Sales,Lynn Daneault,21.0,Monster.com,Fully Meets,1.64,3.0,0.0,2019-01-27,114400.0
23,"Givens, Myriam",1.203032e+09,0.0,0.0,0.0,1.0,6.0,3.0,0.0,55.00,...,Sales,Lynn Daneault,21.0,Pay Per Click - Google,Fully Meets,1.72,5.0,0.0,2019-01-25,114400.0
24,"Jeremy,Prater",1.001085e+09,1.0,1.0,1.0,1.0,6.0,1.0,0.0,56.00,...,Sales,Lynn Daneault,21.0,Website Banner Ads,PIP,1.81,2.0,0.0,2019-01-17,116480.0

In [32]:
df2.head(311)

,EmployeeName,EmployeeID,MarriedID,MaritalStatusID,GenderID,EmpStatusID,DeptID,PerfScoreID,FromDiversityJobFairID,PayRate,...,Department,ManagerName,ManagerID,RecruitmentSource,PerformanceScore,EngagementSurvey,EmpSatisfaction,SpecialProjectsCount,LastPerformanceReviewDate,Salary
0,"Brown, Mia",1.103024e+09,1.0,1.0,0.0,1.0,1.0,3.0,1.0,28.50,...,Admin Offices,Brandon R. LeBlanc,1.0,Diversity Job Fair,Fully Meets,2.04,2.0,6.0,2019-01-15,59280.0
1,"LaRotonda, William",1.106027e+09,0.0,2.0,1.0,1.0,1.0,3.0,0.0,23.00,...,Admin Offices,Brandon R. LeBlanc,1.0,Website Banner Ads,Fully Meets,5.00,4.0,4.0,2019-01-17,47840.0
2,"Steans, Tyrone",1.302053e+09,0.0,0.0,1.0,1.0,1.0,3.0,0.0,29.00,...,Admin Offices,Brandon R. LeBlanc,1.0,Internet Search,Fully Meets,3.90,5.0,5.0,2019-01-18,60320.0
3,"Howard, Estelle",1.211051e+09,1.0,1.0,0.0,1.0,1.0,3.0,0.0,21.50,...,Admin Offices,Brandon R. LeBlanc,1.0,Pay Per Click - Google,Fully Meets,3.24,3.0,4.0,NaT,44720.0
4,"Singh, Nan",1.307060e+09,0.0,0.0,0.0,1.0,1.0,3.0,0.0,16.56,...,Admin Offices,Brandon R. LeBlanc,1.0,Website Banner Ads,Fully Meets,5.00,3.0,5.0,2019-01-15,34444.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
305,"Daniele, Ann",1.411071e+09,1.0,1.0,0.0,3.0,3.0,3.0,0.0,54.10,...,IT/IS,Peter Monroe,7.0,Vendor Referral,Fully Meets,1.55,5.0,8.0,2019-02-12,112528.0
306,"Lajiri, Jyoti",1.108028e+09,1.0,1.0,1.0,3.0,3.0,3.0,0.0,56.20,...,IT/IS,Peter Monroe,7.0,Employee Referral,Fully Meets,4.46,5.0,6.0,2019-01-07,116896.0
307,"Semizoglou, Jeremiah",9.040136e+08,1.0,1.0,1.0,2.0,3.0,3.0,0.0,53.80,...,IT/IS,Peter Monroe,7.0,On-campus Recruiting,Fully Meets,3.27,4.0,5.0,2019-01-14,111904.0
308,"South, Joe",1.308061e+09,0.0,0.0,1.0,1.0,3.0,3.0,0.0,53.00,...,IT/IS,Peter Monroe,7.0,Employee Referral,Fully Meets,5.00,3.0,4.0,2019-01-02,110240.0
309,"Warfield, Sarah",1.301052e+09,0.0,4.0,0.0,1.0,3.0,3.0,0.0,55.20,...,IT/IS,Peter Monroe,7.0,Employee Referral,Fully Meets,1.06,4.0,8.0,2019-02-05,114816.0

In [33]:
def split_name(Name):
    splitval = str(Name).split(',')
    last_name, first_name = splitval[0], splitval[1]
    return [last_name, first_name]

In [34]:
df2['EmployeeLastName'], df2['EmployeeFirstName'] = zip(*df2.apply(lambda x: split_name(x['EmployeeName']), axis=1))

C:\Users\Ron\Anaconda3\envs\dsi04\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [35]:
df2

,EmployeeName,EmployeeID,MarriedID,MaritalStatusID,GenderID,EmpStatusID,DeptID,PerfScoreID,FromDiversityJobFairID,PayRate,...,ManagerID,RecruitmentSource,PerformanceScore,EngagementSurvey,EmpSatisfaction,SpecialProjectsCount,LastPerformanceReviewDate,Salary,EmployeeLastName,EmployeeFirstName
0,"Brown, Mia",1.103024e+09,1.0,1.0,0.0,1.0,1.0,3.0,1.0,28.50,...,1.0,Diversity Job Fair,Fully Meets,2.04,2.0,6.0,2019-01-15,59280.0,Brown,Mia
1,"LaRotonda, William",1.106027e+09,0.0,2.0,1.0,1.0,1.0,3.0,0.0,23.00,...,1.0,Website Banner Ads,Fully Meets,5.00,4.0,4.0,2019-01-17,47840.0,LaRotonda,William
2,"Steans, Tyrone",1.302053e+09,0.0,0.0,1.0,1.0,1.0,3.0,0.0,29.00,...,1.0,Internet Search,Fully Meets,3.90,5.0,5.0,2019-01-18,60320.0,Steans,Tyrone
3,"Howard, Estelle",1.211051e+09,1.0,1.0,0.0,1.0,1.0,3.0,0.0,21.50,...,1.0,Pay Per Click - Google,Fully Meets,3.24,3.0,4.0,NaT,44720.0,Howard,Estelle
4,"Singh, Nan",1.307060e+09,0.0,0.0,0.0,1.0,1.0,3.0,0.0,16.56,...,1.0,Website Banner Ads,Fully Meets,5.00,3.0,5.0,2019-01-15,34444.8,Singh,Nan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
305,"Daniele, Ann",1.411071e+09,1.0,1.0,0.0,3.0,3.0,3.0,0.0,54.10,...,7.0,Vendor Referral,Fully Meets,1.55,5.0,8.0,2019-02-12,112528.0,Daniele,Ann
306,"Lajiri, Jyoti",1.108028e+09,1.0,1.0,1.0,3.0,3.0,3.0,0.0,56.20,...,7.0,Employee Referral,Fully Meets,4.46,5.0,6.0,2019-01-07,116896.0,Lajiri,Jyoti
307,"Semizoglou, Jeremiah",9.040136e+08,1.0,1.0,1.0,2.0,3.0,3.0,0.0,53.80,...,7.0,On-campus Recruiting,Fully Meets,3.27,4.0,5.0,2019-01-14,111904.0,Semizoglou,Jeremiah
308,"South, Joe",1.308061e+09,0.0,0.0,1.0,1.0,3.0,3.0,0.0,53.00,...,7.0,Employee Referral,Fully Meets,5.00,3.0,4.0,2019-01-02,110240.0,South,Joe
309,"Warfield, Sarah",1.301052e+09,0.0,4.0,0.0,1.0,3.0,3.0,0.0,55.20,...,7.0,Employee Referral,Fully Meets,1.06,4.0,8.0,2019-02-05,114816.0,Warfield,Sarah

In [36]:
df2.drop('EmployeeName', axis = 1, inplace = True)

In [37]:
df2

,EmployeeID,MarriedID,MaritalStatusID,GenderID,EmpStatusID,DeptID,PerfScoreID,FromDiversityJobFairID,PayRate,Termd,...,ManagerID,RecruitmentSource,PerformanceScore,EngagementSurvey,EmpSatisfaction,SpecialProjectsCount,LastPerformanceReviewDate,Salary,EmployeeLastName,EmployeeFirstName
0,1.103024e+09,1.0,1.0,0.0,1.0,1.0,3.0,1.0,28.50,0.0,...,1.0,Diversity Job Fair,Fully Meets,2.04,2.0,6.0,2019-01-15,59280.0,Brown,Mia
1,1.106027e+09,0.0,2.0,1.0,1.0,1.0,3.0,0.0,23.00,0.0,...,1.0,Website Banner Ads,Fully Meets,5.00,4.0,4.0,2019-01-17,47840.0,LaRotonda,William
2,1.302053e+09,0.0,0.0,1.0,1.0,1.0,3.0,0.0,29.00,0.0,...,1.0,Internet Search,Fully Meets,3.90,5.0,5.0,2019-01-18,60320.0,Steans,Tyrone
3,1.211051e+09,1.0,1.0,0.0,1.0,1.0,3.0,0.0,21.50,1.0,...,1.0,Pay Per Click - Google,Fully Meets,3.24,3.0,4.0,NaT,44720.0,Howard,Estelle
4,1.307060e+09,0.0,0.0,0.0,1.0,1.0,3.0,0.0,16.56,0.0,...,1.0,Website Banner Ads,Fully Meets,5.00,3.0,5.0,2019-01-15,34444.8,Singh,Nan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
305,1.411071e+09,1.0,1.0,0.0,3.0,3.0,3.0,0.0,54.10,0.0,...,7.0,Vendor Referral,Fully Meets,1.55,5.0,8.0,2019-02-12,112528.0,Daniele,Ann
306,1.108028e+09,1.0,1.0,1.0,3.0,3.0,3.0,0.0,56.20,0.0,...,7.0,Employee Referral,Fully Meets,4.46,5.0,6.0,2019-01-07,116896.0,Lajiri,Jyoti
307,9.040136e+08,1.0,1.0,1.0,2.0,3.0,3.0,0.0,53.80,0.0,...,7.0,On-campus Recruiting,Fully Meets,3.27,4.0,5.0,2019-01-14,111904.0,Semizoglou,Jeremiah
308,1.308061e+09,0.0,0.0,1.0,1.0,3.0,3.0,0.0,53.00,0.0,...,7.0,Employee Referral,Fully Meets,5.00,3.0,4.0,2019-01-02,110240.0,South,Joe
309,1.301052e+09,0.0,4.0,0.0,1.0,3.0,3.0,0.0,55.20,0.0,...,7.0,Employee Referral,Fully Meets,1.06,4.0,8.0,2019-02-05,114816.0,Warfield,Sarah

In [38]:
df2.to_csv(r'C:\Users\Ron\Documents\HRDataset_v13-2.csv')