In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv('C:/Users/Ron/Documents/recruiting_costs.csv')

In [3]:
df

,Employment Source,January,February,March,April,May,June,July,August,September,October,November,December,Total
0,Billboard,520,520,520,520,0,0,612,612,729,749,910,500,6192
1,Careerbuilder,410,410,410,820,820,410,410,820,820,1230,820,410,7790
2,Company Intranet - Partner,0,0,0,0,0,0,0,0,0,0,0,0,0
3,Diversity Job Fair,0,5129,0,0,0,0,0,4892,0,0,0,0,10021
4,Employee Referral,0,0,0,0,0,0,0,0,0,0,0,0,0
5,Glassdoor,0,0,0,0,0,0,0,0,0,0,0,0,0
6,Information Session,0,0,0,0,0,0,0,0,0,0,0,0,0
7,Internet Search,0,0,0,0,0,0,0,0,0,0,0,0,0
8,MBTA ads,640,640,640,640,640,640,640,1300,1300,1300,1300,1300,10980
9,Monster.com,500,500,500,440,500,500,440,500,440,440,500,500,5760
10,Newspager/Magazine,629,510,293,810,642,675,707,740,772,805,838,870,8291
11,On-campus Recruiting,0,0,2500,0,0,2500,0,0,2500,0,0,0,7500
12,On-line Web application,0,0,0,0,0,0,0,0,0,0,0,0,0
13,Other,0,492,0,829,744,0,610,0,0,510,0,810,3995
14,Pay Per Click,110,110,60,121,110,109,130,146,105,109,105,110,1323
15,Pay Per Click - Google,330,330,180,362,197,152,389,437,315,327,315,176,3509
16,Professional Society,100,100,100,100,100,100,100,100,100,100,100,100,1200
17,Search Engine - Google Bing Yahoo,330,410,388,372,472,412,416,495,619,502,389,378,5183
18,Social Networks - Facebook Twitter etc,420,481,452,479,392,508,578,466,389,439,491,478,5573
19,Vendor Referral,0,0,0,0,0,0,0,0,0,0,0,0,0
20,Website Banner Ads,400,400,300,388,592,610,620,669,718,767,816,865,7143
21,Word of Mouth,0,0,0,0,0,0,0,0,0,0,0,0,0

In [4]:
df.dtypes

Employment Source    object
January               int64
February              int64
March                 int64
April                 int64
May                   int64
June                  int64
July                  int64
August                int64
September             int64
October               int64
November              int64
December              int64
Total                 int64
dtype: object

In [5]:
df=df.rename(columns={'Employment Source': 'RecruitmentSource'})

In [6]:
df

,RecruitmentSource,January,February,March,April,May,June,July,August,September,October,November,December,Total
0,Billboard,520,520,520,520,0,0,612,612,729,749,910,500,6192
1,Careerbuilder,410,410,410,820,820,410,410,820,820,1230,820,410,7790
2,Company Intranet - Partner,0,0,0,0,0,0,0,0,0,0,0,0,0
3,Diversity Job Fair,0,5129,0,0,0,0,0,4892,0,0,0,0,10021
4,Employee Referral,0,0,0,0,0,0,0,0,0,0,0,0,0
5,Glassdoor,0,0,0,0,0,0,0,0,0,0,0,0,0
6,Information Session,0,0,0,0,0,0,0,0,0,0,0,0,0
7,Internet Search,0,0,0,0,0,0,0,0,0,0,0,0,0
8,MBTA ads,640,640,640,640,640,640,640,1300,1300,1300,1300,1300,10980
9,Monster.com,500,500,500,440,500,500,440,500,440,440,500,500,5760
10,Newspager/Magazine,629,510,293,810,642,675,707,740,772,805,838,870,8291
11,On-campus Recruiting,0,0,2500,0,0,2500,0,0,2500,0,0,0,7500
12,On-line Web application,0,0,0,0,0,0,0,0,0,0,0,0,0
13,Other,0,492,0,829,744,0,610,0,0,510,0,810,3995
14,Pay Per Click,110,110,60,121,110,109,130,146,105,109,105,110,1323
15,Pay Per Click - Google,330,330,180,362,197,152,389,437,315,327,315,176,3509
16,Professional Society,100,100,100,100,100,100,100,100,100,100,100,100,1200
17,Search Engine - Google Bing Yahoo,330,410,388,372,472,412,416,495,619,502,389,378,5183
18,Social Networks - Facebook Twitter etc,420,481,452,479,392,508,578,466,389,439,491,478,5573
19,Vendor Referral,0,0,0,0,0,0,0,0,0,0,0,0,0
20,Website Banner Ads,400,400,300,388,592,610,620,669,718,767,816,865,7143
21,Word of Mouth,0,0,0,0,0,0,0,0,0,0,0,0,0

In [7]:
df.to_csv(r'C:\Users\Ron\Documents\recruiting_costs2.csv')